apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: ui
    tier: frontend
spec:
  replicas: 2
  selector:  
    matchLabels:
      tier: frontend
  template:
    metadata:
    spec:
      containers:
      - name: app1
        image: supergiantkir/animals:bear
        volumeMounts:
        - name: app-storage
          mountPath: /storage
      - name: app2
        image: yanivomc/spring-music:latest
        volumeMounts:
        - name: app-storage
          mountPath: /storage
      volumes:
      - name: app-storage
        hostPath:
          # directory location on host
          path: /tmp/files
