kind: Service      # Create new service
apiVersion: v1     
metadata:
  name: spring-service # Name of the service
spec:
  selector:
    app: y-spring-music    # Run on any pod(s) with label - app: myapp
  ports:          # Map incoming port to target port
  - name: http    # Setting multiple ports listterns 
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
